version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 12000:80
  wp1:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "12001:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  wp2:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "12002:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp2
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  wp3:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "12003:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp3
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  wp4:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "12004:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp4
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  wp5:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "12005:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp5
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  wp6:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "12006:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp6
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

volumes:
  db_data: